/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.tasks;

import ch.autumo.beetroot.Entity;

/**
 * Task. 
 */
public class Task implements Entity {

    private String monthofyear;

    public String getMonthofyear() {
        return monthofyear;
    }

    public void setMonthofyear(String monthofyear) {
        this.monthofyear = monthofyear;
    }

    private java.sql.Timestamp created;

    public java.sql.Timestamp getCreated() {
        return created;
    }

    public void setCreated(java.sql.Timestamp created) {
        this.created = created;
    }

    private boolean active;

    public boolean getActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    private String minute;

    public String getMinute() {
        return minute;
    }

    public void setMinute(String minute) {
        this.minute = minute;
    }

    private String dayofmonth;

    public String getDayofmonth() {
        return dayofmonth;
    }

    public void setDayofmonth(String dayofmonth) {
        this.dayofmonth = dayofmonth;
    }

    private String path;

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    private String hour;

    public String getHour() {
        return hour;
    }

    public void setHour(String hour) {
        this.hour = hour;
    }

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private String guid;

    public String getGuid() {
        return guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    private String dayofweek;

    public String getDayofweek() {
        return dayofweek;
    }

    public void setDayofweek(String dayofweek) {
        this.dayofweek = dayofweek;
    }

    private boolean laststatus;

    public boolean getLaststatus() {
        return laststatus;
    }

    public void setLaststatus(boolean laststatus) {
        this.laststatus = laststatus;
    }

    private java.sql.Timestamp modified;

    public java.sql.Timestamp getModified() {
        return modified;
    }

    public void setModified(java.sql.Timestamp modified) {
        this.modified = modified;
    }

    private java.sql.Timestamp lastexecuted;

    public java.sql.Timestamp getLastexecuted() {
        return lastexecuted;
    }

    public void setLastexecuted(java.sql.Timestamp lastexecuted) {
        this.lastexecuted = lastexecuted;
    }

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

	
	
}
