/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.models;

import ch.autumo.beetroot.Model;
import ch.autumo.beetroot.annotations.Column;
import ch.autumo.beetroot.annotations.Nullable;
import ch.autumo.beetroot.annotations.Unique;

/**
 * Product. 
 */
public class Product extends Model {

    private static final long serialVersionUID = 1L;
	
    @Column (name = "int_sec_key")
    private String intSecKey;

    public String getIntSecKey() {
        return intSecKey;
    }

    public void setIntSecKey(String intSecKey) {
        this.intSecKey = intSecKey;
    }

    @Nullable
    @Column (name = "email_notes")
    private String emailNotes;

    public String getEmailNotes() {
        return emailNotes;
    }

    public void setEmailNotes(String emailNotes) {
        this.emailNotes = emailNotes;
    }

    @Nullable
    @Column (name = "created")
    private java.sql.Timestamp created;

    public java.sql.Timestamp getCreated() {
        return created;
    }

    public void setCreated(java.sql.Timestamp created) {
        this.created = created;
    }

    @Unique
    @Column (name = "name")
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Nullable
    @Column (name = "modified")
    private java.sql.Timestamp modified;

    public java.sql.Timestamp getModified() {
        return modified;
    }

    public void setModified(java.sql.Timestamp modified) {
        this.modified = modified;
    }

    @Column (name = "create_user")
    private boolean createUser;

    public boolean getCreateUser() {
        return createUser;
    }
    
    @Override
    public String getDisplayField() {
        return "name";
    }

    @Override
    public Class<?> modelClass() {
        return Product.class;
    }	
	
}
