/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.models;

import ch.autumo.beetroot.Model;

/**
 * Product. 
 */
public class Product extends Model {

    private static final long serialVersionUID = 1L;
	
    private String intSecKey;

    public String getIntSecKey() {
        return intSecKey;
    }

    public void setIntSecKey(String intSecKey) {
        this.intSecKey = intSecKey;
    }

    private String emailNotes;

    public String getEmailNotes() {
        return emailNotes;
    }

    public void setEmailNotes(String emailNotes) {
        this.emailNotes = emailNotes;
    }

    private java.sql.Timestamp created;

    public java.sql.Timestamp getCreated() {
        return created;
    }

    public void setCreated(java.sql.Timestamp created) {
        this.created = created;
    }

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private java.sql.Timestamp modified;

    public java.sql.Timestamp getModified() {
        return modified;
    }

    public void setModified(java.sql.Timestamp modified) {
        this.modified = modified;
    }

    private boolean createUser;

    public boolean getCreateUser() {
        return createUser;
    }

    public void setCreateUser(boolean createUser) {
        this.createUser = createUser;
    }

    @Override
    public String getDisplayField() {
        return "name";
    }

    @Override
    public Class<?> modelClass() {
        return Product.class;
    }	
	
}
