/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.users;

import ch.autumo.beetroot.Entity;

/**
 * User. 
 */
public class User implements Entity {

    private static final long serialVersionUID = 1L;
    
	private String firstname;

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    private String role;

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    private String lasttoken;

    public String getLasttoken() {
        return lasttoken;
    }

    public void setLasttoken(String lasttoken) {
        this.lasttoken = lasttoken;
    }

    private java.sql.Timestamp created;

    public java.sql.Timestamp getCreated() {
        return created;
    }

    public void setCreated(java.sql.Timestamp created) {
        this.created = created;
    }

    private java.sql.Timestamp modified;

    public java.sql.Timestamp getModified() {
        return modified;
    }

    public void setModified(java.sql.Timestamp modified) {
        this.modified = modified;
    }

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    private String lang;

    public String getLang() {
        return lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    private String email;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    private String lastname;

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    private String secretkey;
    
    public String getSecretkey() {
		return secretkey;
	}
	
    public void setSecretkey(String secretkey) {
		this.secretkey = secretkey;		
	}
    
    private boolean twoFa;
    
    public boolean getTwoFa() {
    	return twoFa;
    }

    public void setTwoFa(boolean twoFa) {
    	this.twoFa = twoFa;
    }
    
}
