/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package planted.beetroot.handler.properties;

import java.sql.ResultSet;

import ch.autumo.beetroot.Session;
//import ch.autumo.beetroot.Utils;
import ch.autumo.beetroot.handler.DefaultViewHandler;

/**
 * Properties view handler. 
 */
public class PropertiesViewHandler extends DefaultViewHandler {
	
	public PropertiesViewHandler(String entity) {
		super(entity);
	}

	@Override
	public String extractSingleTableData(ResultSet set, String columnName, int idx) throws Exception {
		
		switch (columnName) {
			// Note: Return a UI presentable value for each field.
			// The class 'Utils' provides some helper methods for this.
			// PS: Customize style for <td> if necessary.
			case "name": return "<td>" + set.getString(columnName) + "</td>";
			case "value": return "<td>" + set.getString(columnName) + "</td>";
			default: return "<td>"+set.getObject(columnName)+"</td>";
		}
	}

	@Override
	public boolean hasAccess(Session userSession) {
		return userSession.getUserRole().equalsIgnoreCase("administrator");
	}
	
}
