/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package planted.beetroot.handler.properties;

import java.sql.ResultSet;

import ch.autumo.beetroot.Session;
//import ch.autumo.beetroot.Utils;
import ch.autumo.beetroot.handler.DefaultIndexHandler;

/**
 * Properties index handler.
 */
public class PropertiesIndexHandler extends DefaultIndexHandler {

	public PropertiesIndexHandler(String entity) {
		super(entity);
	}

	public PropertiesIndexHandler(String entity, String msg) {

		super(entity);
		
		super.addSuccessMessage(msg);
		super.redirectedMarker(true);
	}
	
	@Override
	public String extractSingleTableData(ResultSet set, String columnName, int idx) throws Exception {
		
		switch (columnName) {
			// Note: Return a UI presentable value for each field.
			// The class 'Utils' provides some helper methods for this.
			// PS: Customize style for <td> if necessary.
			case "modified": return "<td>" + set.getString(columnName) + "</td>";
			case "value": return "<td>" + set.getString(columnName) + "</td>";
			default: return "<td>" + set.getObject(columnName) + "</td>";
		}
	}

	@Override
	public boolean hasAccess(Session userSession) {
		return userSession.getUserRole().equalsIgnoreCase("administrator");
	}
	
}
