/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.usersroles;

import ch.autumo.beetroot.Model;
import ch.autumo.beetroot.annotations.Column;
import ch.autumo.beetroot.annotations.Nullable;
import ch.autumo.beetroot.handler.roles.Role;
import ch.autumo.beetroot.handler.users.User;

/**
 * UserRole. 
 */
public class UserRole extends Model {

    private static final long serialVersionUID = 1L;
	
    @Column (name = "user_id")
    private int userId;

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column (name = "role_id")
    private int roleId;

    public int getRoleId() {
        return roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    @Nullable
    @Column (name = "created")
    private java.sql.Timestamp created;

    public java.sql.Timestamp getCreated() {
        return created;
    }

    public void setCreated(java.sql.Timestamp created) {
        this.created = created;
    }

    @Override
    public String getDisplayField() {
        return "id";
    }

    @Override
    public java.util.Map<String, Class<?>> getForeignReferences() {
        return java.util.Map.ofEntries(
                java.util.Map.entry("role_id", Role.class),
                java.util.Map.entry("user_id", User.class)
            );
    }

    @Override
    public Class<?> modelClass() {
        return UserRole.class;
    }	
	
}
