/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package planted.beetroot.handler.properties;

import ch.autumo.beetroot.Model;

/**
 * Property. 
 */
public class Property extends Model {

    private static final long serialVersionUID = 1L;
	
    private java.sql.Timestamp created;

    public java.sql.Timestamp getCreated() {
        return created;
    }

    public void setCreated(java.sql.Timestamp created) {
        this.created = created;
    }

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private java.sql.Timestamp modified;

    public java.sql.Timestamp getModified() {
        return modified;
    }

    public void setModified(java.sql.Timestamp modified) {
        this.modified = modified;
    }

    private String value;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

	@Override
	public String getDisplayField() {
		return "name";
	}
    
	@Override
	public Class<?> modelClass() {
		return Property.class;
	}
	
}
