/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package planted.beetroot.handler.properties;

import ch.autumo.beetroot.BeetRootHTTPSession;
import ch.autumo.beetroot.Session;
import ch.autumo.beetroot.handler.DefaultDeleteHandler;
import ch.autumo.beetroot.handler.HandlerResponse;
import ch.autumo.beetroot.utils.DB;

/**
 * Properties add handler. 
 */
public class PropertiesDeleteHandler extends DefaultDeleteHandler {
	
	public PropertiesDeleteHandler(String entity) {
		super(entity);
	}
	
	@Override
	public Class<?> getRedirectHandler() {
		return PropertiesIndexHandler.class;
	}

	@Override
	public HandlerResponse deleteData(BeetRootHTTPSession session, int id) throws Exception {

		// if you need the bean before deleting the database object
		Property property = (Property) DB.selectRecord(Property.class, id);

		super.deleteData(session, id); // delete it in the database
		
		return null; // ok
	}

	@Override
	public boolean hasAccess(Session userSession) {
		return userSession.getUserRole().equalsIgnoreCase("Administrator");
	}
	
}
