/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.users;

import ch.autumo.beetroot.Model;
import ch.autumo.beetroot.annotations.Column;
import ch.autumo.beetroot.annotations.Unique;

/**
 * User. 
 */
public class User extends Model {

    private static final long serialVersionUID = 1L;
    
    @Column (name = "firstname")
	private String firstname;

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column (name = "password")
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column (name = "role")
    private String role;

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Column (name = "lasttoken")
    private String lasttoken;

    public String getLasttoken() {
        return lasttoken;
    }

    public void setLasttoken(String lasttoken) {
        this.lasttoken = lasttoken;
    }

    @Column (name = "created")
    private java.sql.Timestamp created;

    public java.sql.Timestamp getCreated() {
        return created;
    }

    public void setCreated(java.sql.Timestamp created) {
        this.created = created;
    }

    @Column (name = "modified")
    private java.sql.Timestamp modified;

    public java.sql.Timestamp getModified() {
        return modified;
    }

    public void setModified(java.sql.Timestamp modified) {
        this.modified = modified;
    }

    @Column (name = "lang")
    private String lang;

    public String getLang() {
        return lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    @Unique
    @Column (name = "email")
    private String email;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Unique
    @Column (name = "phone")
    private String phone;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Unique
    @Column (name = "username")
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column (name = "lastname")
    private String lastname;

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column (name = "secretkey")
    private String secretkey;
    
    public String getSecretkey() {
		return secretkey;
	}
	
    public void setSecretkey(String secretkey) {
		this.secretkey = secretkey;
	}
    
    @Column (name = "two_fa")
    private boolean twoFa;
    
    public boolean getTwoFa() {
    	return twoFa;
    }

    public void setTwoFa(boolean twoFa) {
    	this.twoFa = twoFa;
    }

	@Override
	public String getDisplayField() {
		return "username";
	}

	@Override
	public Class<?> modelClass() {
		return User.class;
	}
    
}
