/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.roles;

import ch.autumo.beetroot.handler.DefaultEditHandler;

/**
 * Roles edit handler. 
 */
public class RolesEditHandler extends DefaultEditHandler {
	
	public RolesEditHandler(String entity) {
		super(entity);
	}

	public RolesEditHandler(String entity, String errMsg) {
		super(entity, errMsg);
	}
	
	@Override
	public Class<?> getRedirectHandler() {
		return RolesIndexHandler.class;
	}

	@Override
	public Class<?> getBeanClass() {
		return Role.class;
	}
	
}
