/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.roles;

import java.util.Map;

import ch.autumo.beetroot.Session;
import ch.autumo.beetroot.handler.DefaultAddHandler;

/**
 * Roles add handler. 
 */
public class RolesAddHandler extends DefaultAddHandler {
	
	public RolesAddHandler(String entity) {
		super(entity);
	}

	public RolesAddHandler(String entity, String errMsg) {
		super(entity, errMsg);
	}
	
	@Override
	public Class<?> getRedirectHandler() {
		return RolesIndexHandler.class;
	}

	@Override
	public Map<String, Object> getAddMandatoryFields() {
		//We have no mandatory fields that aren't shown on the UI
		return null;
	}

	@Override
	public boolean hasAccess(Session userSession) {
		return userSession.hasUserRole("Administrator");
	}
	
	@Override
	public Class<?> getBeanClass() {
		return Role.class;
	}
	
}
