/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.roles;

import ch.autumo.beetroot.BeetRootHTTPSession;
import ch.autumo.beetroot.handler.HandlerResponse;
import ch.autumo.beetroot.utils.DB;

import ch.autumo.beetroot.handler.DefaultDeleteHandler;

/**
 * Roles add handler. 
 */
public class RolesDeleteHandler extends DefaultDeleteHandler {
	
	public RolesDeleteHandler(String entity) {
		super(entity);
	}
	
	@Override
	public Class<?> getRedirectHandler() {
		return RolesIndexHandler.class;
	}

	@Override
	public HandlerResponse deleteData(BeetRootHTTPSession session, int id) throws Exception {

		// if you need the bean before deleting the database object
		Role role = (Role) DB.selectRecord(Role.class, id);

		return super.deleteData(session, id); // delete it in the database
	}
	
}
