/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.roles;

import ch.autumo.beetroot.Session;
import ch.autumo.beetroot.handler.DefaultDeleteHandler;

/**
 * Roles delete handler. 
 * Cascade deletes associated UserRole.
 */
public class RolesDeleteHandler extends DefaultDeleteHandler {
	
	public RolesDeleteHandler(String entity) {
		super(entity);
	}
	
	@Override
	public Class<?> getRedirectHandler() {
		return RolesIndexHandler.class;
	}

	@Override
	public boolean hasAccess(Session userSession) {
		return userSession.getUserRoles().contains("Administrator");
	}
	
	@Override
	public Class<?> getBeanClass() {
		return Role.class;
	}	
}
