/**
 * Generated by PLANT - beetRoot CRUD Generator.
 */
package ch.autumo.beetroot.handler.roles;

import java.util.HashMap;
import java.util.Map;

import ch.autumo.beetroot.handler.DefaultAddHandler;

/**
 * Roles add handler. 
 */
public class RolesAddHandler extends DefaultAddHandler {
	
	public RolesAddHandler(String entity) {
		super(entity);
	}

	public RolesAddHandler(String entity, String errMsg) {
		super(entity, errMsg);
	}
	
	@Override
	public Class<?> getRedirectHandler() {
		return RolesIndexHandler.class;
	}

	@Override
	public Map<String, Object> getAddMandatoryFields() {
		
		final Map<String, Object> fields = new HashMap<String, Object>();
		
		// NOTE: Provide default values for fields that are NOT
		// nullable and that aren't present in the add GUI!
		// If these fields are present in the GUI, you can remove
		// them or simply return null here!
		// fields.put("name", "<DEFAULT-VALUE>");
		// fields.put("id", "<DEFAULT-VALUE>");

		return fields;
	}

	@Override
	public Class<?> getBeanClass() {
		return Role.class;
	}
	
}
